### Importacion de librerias

In [67]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import os
import janitor
################
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
################

### Carga de datos

In [50]:
df = pd.read_csv("precio_mayorista_fruta-hortaliza_2025.csv")
df = df.clean_names()
df.head()

,fecha,id_region,region,mercado,subsector,producto,variedad_tipo,calidad,unidad_de_comercializacion,origen,volumen,precio_minimo,precio_maximo,precio_promedio_ponderado
0,2025-01-02,5,Región de Valparaíso,Femacal de La Calera,Hortalizas y tubérculos,Acelga,Sin especificar,Primera,$/docena de atados (6 kilos),Provincia de Quillota,110,"4000,0000","4000,0000","4000,0000"
1,2025-01-02,8,Región del Biobío,Vega Monumental Concepción,Hortalizas y tubérculos,Acelga,Sin especificar,Primera,"$/atado 0,5 a 1 kilo",Región Metropolitana,300,"800,0000","800,0000","800,0000"
2,2025-01-02,16,Región de Ñuble,Terminal Hortofrutícola Agro Chillán,Hortalizas y tubérculos,Acelga,Sin especificar,Primera,"$/atado 0,5 a 1 kilo",Región de Ñuble,200,"600,0000","600,0000","600,0000"
3,2025-01-02,16,Región de Ñuble,Terminal Hortofrutícola Agro Chillán,Hortalizas y tubérculos,Acelga,Sin especificar,Segunda,"$/atado 0,5 a 1 kilo",Región de Ñuble,600,"500,0000","500,0000","500,0000"
4,2025-01-02,4,Región de Coquimbo,Terminal La Palmera de La Serena,Hortalizas y tubérculos,Ají,Inferno,Primera,$/caja 15 kilos,Provincia de Limarí,400,"15000,0000","17000,0000","16000,0000"

### Analisis descriptivo

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113511 entries, 0 to 113510
Data columns (total 14 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Fecha                       113511 non-null  object
 1   ID region                   113511 non-null  int64
 2   Region                      113511 non-null  object
 3   Mercado                     113511 non-null  object
 4   Subsector                   113511 non-null  object
 5   Producto                    113511 non-null  object
 6   Variedad / Tipo             113511 non-null  object
 7   Calidad                     113511 non-null  object
 8   Unidad de comercializacion  113511 non-null  object
 9   Origen                      113511 non-null  object
 10  Volumen                     113511 non-null  int64
 11  Precio minimo               113511 non-null  object
 12  Precio maximo               113511 non-null  object
 13  Precio promedio ponderado   113511 non-null  object
dtypes: int64(2), object(12)
memory usage: 12.1+ MB

In [18]:
df.nunique()

Fecha                           137
ID region                         9
Region                            9
Mercado                          12
Subsector                         2
Producto                         81
Variedad / Tipo                 222
Calidad                          48
Unidad de comercializacion      143
Origen                           61
Volumen                        1302
Precio minimo                   332
Precio maximo                   287
Precio promedio ponderado     11209
dtype: int64

In [19]:
df.describe(include= "all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Fecha,113511,137,2025-02-11,1009,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ID region,113511.0,NaN,NaN,NaN,10.098246,3.820852,4.0,7.0,10.0,13.0,16.0
Region,113511,9,Región Metropolitana de Santiago,44826,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Mercado,113511,12,Mercado Mayorista Lo Valledor de Santiago,29088,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Subsector,113511,2,Hortalizas y tubérculos,64351,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Producto,113511,81,Palta,6870,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Variedad / Tipo,113511,222,Sin especificar,41440,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Calidad,113511,48,Primera,57223,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Unidad de comercializacion,113511,143,$/unidad,10950,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Origen,113511,61,Región de O'Higgins,23417,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Volumen,113511.0,NaN,NaN,NaN,1090.297231,6317.001326,1.0,100.0,240.0,520.0,269000.0
Precio minimo,113511,332,"10000,0000",5683,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Precio maximo,113511,287,"10000,0000",6056,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Precio promedio ponderado,113511,11209,"10000,0000",4306,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df.head()

,Fecha,ID region,Region,Mercado,Subsector,Producto,Variedad / Tipo,Calidad,Unidad de comercializacion,Origen,Volumen,Precio minimo,Precio maximo,Precio promedio ponderado
0,2025-01-02,5,Región de Valparaíso,Femacal de La Calera,Hortalizas y tubérculos,Acelga,Sin especificar,Primera,$/docena de atados (6 kilos),Provincia de Quillota,110,"4000,0000","4000,0000","4000,0000"
1,2025-01-02,8,Región del Biobío,Vega Monumental Concepción,Hortalizas y tubérculos,Acelga,Sin especificar,Primera,"$/atado 0,5 a 1 kilo",Región Metropolitana,300,"800,0000","800,0000","800,0000"
2,2025-01-02,16,Región de Ñuble,Terminal Hortofrutícola Agro Chillán,Hortalizas y tubérculos,Acelga,Sin especificar,Primera,"$/atado 0,5 a 1 kilo",Región de Ñuble,200,"600,0000","600,0000","600,0000"
3,2025-01-02,16,Región de Ñuble,Terminal Hortofrutícola Agro Chillán,Hortalizas y tubérculos,Acelga,Sin especificar,Segunda,"$/atado 0,5 a 1 kilo",Región de Ñuble,600,"500,0000","500,0000","500,0000"
4,2025-01-02,4,Región de Coquimbo,Terminal La Palmera de La Serena,Hortalizas y tubérculos,Ají,Inferno,Primera,$/caja 15 kilos,Provincia de Limarí,400,"15000,0000","17000,0000","16000,0000"

In [22]:
df.columns

Index(['Fecha', 'ID region', 'Region', 'Mercado', 'Subsector', 'Producto',
       'Variedad / Tipo', 'Calidad', 'Unidad de comercializacion', 'Origen',
       'Volumen', 'Precio minimo', 'Precio maximo',
       'Precio promedio ponderado'],
      dtype='object')

In [11]:
df.head(5)

,fecha,id_region,region,mercado,subsector,producto,variedad_tipo,calidad,unidad_de_comercializacion,origen,volumen,precio_minimo,precio_maximo,precio_promedio_ponderado
0,2025-01-02,5,Región de Valparaíso,Femacal de La Calera,Hortalizas y tubérculos,Acelga,Sin especificar,Primera,$/docena de atados (6 kilos),Provincia de Quillota,110,"4000,0000","4000,0000","4000,0000"
1,2025-01-02,8,Región del Biobío,Vega Monumental Concepción,Hortalizas y tubérculos,Acelga,Sin especificar,Primera,"$/atado 0,5 a 1 kilo",Región Metropolitana,300,"800,0000","800,0000","800,0000"
2,2025-01-02,16,Región de Ñuble,Terminal Hortofrutícola Agro Chillán,Hortalizas y tubérculos,Acelga,Sin especificar,Primera,"$/atado 0,5 a 1 kilo",Región de Ñuble,200,"600,0000","600,0000","600,0000"
3,2025-01-02,16,Región de Ñuble,Terminal Hortofrutícola Agro Chillán,Hortalizas y tubérculos,Acelga,Sin especificar,Segunda,"$/atado 0,5 a 1 kilo",Región de Ñuble,600,"500,0000","500,0000","500,0000"
4,2025-01-02,4,Región de Coquimbo,Terminal La Palmera de La Serena,Hortalizas y tubérculos,Ají,Inferno,Primera,$/caja 15 kilos,Provincia de Limarí,400,"15000,0000","17000,0000","16000,0000"

In [ ]:
var_num = ['volumen', 'precio_minimo', 'precio_maximo', 'precio_promedio_ponderado']
df[var_num] = df[var_num].replace(',', '.', regex = True).astype(float).round(0).astype('Int64')
df["fecha"] = pd.to_datetime(df["fecha"],format='%Y-%m-%d')

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113511 entries, 0 to 113510
Data columns (total 14 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   fecha                       113511 non-null  datetime64[ns]
 1   id_region                   113511 non-null  int64
 2   region                      113511 non-null  object
 3   mercado                     113511 non-null  object
 4   subsector                   113511 non-null  object
 5   producto                    113511 non-null  object
 6   variedad_tipo               113511 non-null  object
 7   calidad                     113511 non-null  object
 8   unidad_de_comercializacion  113511 non-null  object
 9   origen                      113511 non-null  object
 10  volumen                     113511 non-null  Int64
 11  precio_minimo               113511 non-null  Int64
 12  precio_maximo               113511 non-null  Int64
 13  precio_promedio_ponderado   113511 non-null  Int64
dtypes: Int64(4), datetime64[ns](1), int64(1), object(8)
memory usage: 12.6+ MB

In [66]:
df[['volumen', 'precio_minimo', 'precio_maximo', 'precio_promedio_ponderado', 'producto']]

,volumen,precio_minimo,precio_maximo,precio_promedio_ponderado,producto
0,110,4000,4000,4000,Acelga
1,300,800,800,800,Acelga
2,200,600,600,600,Acelga
3,600,500,500,500,Acelga
4,400,15000,17000,16000,Ají
...,...,...,...,...,...
113506,520,5000,5200,5100,Cebollín
113507,900,5000,5000,5000,Cebollín
113508,340,4000,4500,4250,Cebollín
113509,600,4500,4500,4500,Cebollín
113510,500,3800,3800,3800,Cebollín